spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cust_master
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: flase
