global:
  message: Welcome to order service dev environment
server:
  port: 8084
message: Hello from order Dev
spring:
  datasource:
    url: jdbc:h2:mem:order_master
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
