global:
  message: Welcome to order service prod environment
server:
  port: 8085
message: Hello from order Prod !
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_prod
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
