
global:
  message: Welcome to User service prod environment
server:
  port: 8086
message: Hello from Prod !
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_prod
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
